#The next approximation should be generated by using the function values at both boundaries.
#f(x)
#a,b,print f(a),f(b)
#Rounds , Es
#mid berkorte hobe
#for loop er bitore formula apply korbo
#i>0 error berkorbo
#er<Es tahole break korbe
#f(a) * f(x) < 0 tahole b = x else a = x and x_old = x

def f(x):
    return x**2-7
a = 2
b = 3
print(f(a),f(b))
Es = 0.01
mid = (a+b)/2
for i in range(20):
    mid_new = (a*f(b) - b*f(a))/(f(b)-f(a))
    if i>0:
        error = abs(mid_new - mid)
        print("Iteration = ",i,"a = ",a,"b = ",b,"mid_new = ",mid,"Error = ",error)

        Er = abs((mid_new-mid)/mid_new)*100

        if Er<Es:
            break
    if f(a) * f(mid_new) < 0:
        b = mid_new
    else:
        a = mid_new
    mid = mid_new
print("Iteartion: ",i+1)
print("Root: ",round(mid_new,4))
